//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
//using System.Data.EntityClient;
//using System.Data.Objects;
//using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

//[assembly: EdmSchemaAttribute()]
namespace WindowsFormsApp1
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    /// 
    /*
    public partial class SupermarkertModel1Container : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new SupermarkertModel1Container object using the connection string found in the 'SupermarkertModel1Container' section of the application configuration file.
        /// </summary>
        public SupermarkertModel1Container() : base("name=SupermarkertModel1Container", "SupermarkertModel1Container")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SupermarkertModel1Container object.
        /// </summary>
        public SupermarkertModel1Container(string connectionString) : base(connectionString, "SupermarkertModel1Container")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SupermarkertModel1Container object.
        /// </summary>
        public SupermarkertModel1Container(EntityConnection connection) : base(connection, "SupermarkertModel1Container")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    */
    
        #endregion
    
        #region Partial Methods
    
    /*
        partial void OnContextCreated();
    
        #endregion
    
    }
    */
    #endregion
    

}
