//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace WindowsFormsApp1
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class SupermarketModel1Container : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new SupermarketModel1Container object using the connection string found in the 'SupermarketModel1Container' section of the application configuration file.
        /// </summary>
        public SupermarketModel1Container() : base("name=SupermarketModel1Container", "SupermarketModel1Container")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SupermarketModel1Container object.
        /// </summary>
        public SupermarketModel1Container(string connectionString) : base(connectionString, "SupermarketModel1Container")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SupermarketModel1Container object.
        /// </summary>
        public SupermarketModel1Container(EntityConnection connection) : base(connection, "SupermarketModel1Container")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
    }

    #endregion

}
